name: Checks

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup install nightly --profile default
      - run: rustup default nightly
      - run: cargo clippy --all-targets --all-features -- --deny warnings

  test-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup default 1.88
      - run: cargo test --release
